### ISSUE TITLE
mailalias doesn't exist

### ISSUE THREAD

**Issue by TexasSTX** [Puppet-Finland/puppet-postfix#7]
works flawlessly on a CentOS 6 installation, but on my CentOS 7 installation, I get the following error when attempting to include the postfix class:

 Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Virtual Query, Resource type mailalias doesn't exist (file: /etc/puppetlabs/code/environments/test/modules/postfix/manifests/config.pp, line: 96, column: 5)

Verified mailalias.pp is in the manifests file

**Comment by TexasSTX** [comment]
added puppetlabs/mailalias_core as dependency and it was resolved

**Comment by mattock** [comment]
Yes, Puppet 6 moves several core resources into external modules. I'm not exactly sure yet if those new dependencies should be included in metadata.json or if they cause issues on Puppet 5.

**Comment by mattock** [comment]
That is, if loading the dependencies with a tool like puppet-librarian will break things on Puppet 5. Probably not, but will need to test.
